# Generated by Django 3.0.3 on 2020-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='closed_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hashtag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='open_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='weekend',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
