# Generated by Django 3.0.3 on 2020-08-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20200817_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='hashtag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='weekend',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
