# Generated by Django 3.0.3 on 2020-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20200818_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='closed_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='weekend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
